spring:
  application:
    name: home-appliances

  datasource:
    url: jdbc:mysql://localhost:3306/appliances?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

security:
  jwt:
    secret-key: TVwecGTXvumwWVCk3aFspQeprBoYnxEt8AaQ3kpFTuk=
    expiration-time: 3600000


